spring:
  application:
    name: tlias
  #mysql????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
mybatis-plus:
  mapper-locations: classpath:*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: wzml-java-01
    region: cn-beijing
    access-key-id: LTAI5tGymxxcKm95qNdMAbHn
    access-key-secret: bgXpLi1Pq4I6gimOD7pkZ2I7q0iG9C